dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

env:
  - SCRIPT=travis-openjdk8.sh
  - SCRIPT=travis-oraclejdk8.sh
  - SCRIPT=travis-coverage.sh
  - SCRIPT=travis-jar.sh
  - SCRIPT=travis-dspot-maven.sh
  - SCRIPT=travis-checkstyle.sh

cache:
  directories:
    - $HOME/.m2

install:
  - export DSPOT_VERSION=`grep '<version>' dspot/pom.xml | head -n 1 | sed -e 's/<version>//' -e 's/<\\/version>//' -e 's/ *//g'`
  - export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'`
  - mvn compile
  - cd dspot && ./src/main/bash/update-classes-in-resources.sh
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true
  - cd ..

script:
  - ./.travis/$SCRIPT $DSPOT_VERSION

after_success:
  - ./.travis/travis-deploy.sh

branch:
  only:
    - master
deploy:
   provider: heroku
   api_key: 61e0649e-43b4-4a9b-8190-a9302a86764d