language: java
sudo: false
script: mvn clean verify
jdk:
- oraclejdk8

before_install:
  - chmod +x mvnw

install:
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test:
mvn test -B
./mvnw test -B

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
   provider: heroku
   api_key: 61e0649e-43b4-4a9b-8190-a9302a86764d